# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Add global configuration
global:
  configMapName: microservices-config

deploymentName: cards-deployment
serviceName: cards
appLabel: cards
appName: cards

replicaCount: 1

image:
  repository: rudro77/cards
  tag: 0.0.1-SNAPSHOT

containerPort: 9000

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false

# Add database configuration
database:
  enabled: true
  name: cardsdb
  dbname: cardsdb
  username: root
  password: root
  port: 3306
  storage: 1Gi
  url: jdbc:mysql://cardsdb:3306/cardsdb
