global:
  configMapName: microservices-bank-prod-configmap
  activeProfile: prod
  configServerURL: configserver:http://configserver:8071/
  eurekaServerURL: http://eurekaserver:8070/eureka/
  keyCloakURL: http://keycloak.default.svc.cluster.local:80/realms/master/protocol/openid-connect/certs
  openTelemetryJavaAgent: "-javaagent:/app/libs/opentelemetry-javaagent-1.27.0.jar"
  otelExporterEndPoint: http://tempo-grafana-tempo-distributor:4318
  otelMetricsExporter: none
  otelLogsExporter: none
  kafkaBrokerURL: kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092

accounts:
  database:
    enabled: true
    name: accountsdb
    dbname: accountsdb
    username: root
    password: root
    port: 3306
    storage: 1Gi
    url: "jdbc:mysql://accountsdb:3306/accountsdb"

  initContainer:
    enabled: true
    image: mysql:8.0.41
