{{/* Use ONLY one database template */}}
{{- if and .Values.database.enabled (not (lookup "apps/v1" "StatefulSet" .Release.Namespace .Values.database.name)) -}}
{{- template "common.database" . -}}
{{- end -}}

{{/* Then explicitly delete the mysql-deployment if it exists */}}
{{- define "charts/accounts/templates/mysql-deployment.yaml" -}}
{{- end -}}

{{/* Single database definition */}}
{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.database.name }}
spec:
  serviceName: {{ .Values.database.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.database.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.name }}
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.database.password }}
        - name: MYSQL_DATABASE
          value: {{ .Values.database.dbname }}
        ports:
        - containerPort: {{ .Values.database.port }}
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.database.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
spec:
  ports:
  - port: {{ .Values.database.port }}
    targetPort: mysql
  clusterIP: None
  selector:
    app: {{ .Values.database.name }}
{{- end }} 