build:
  version: "3.0"
accounts:
  message: "Welcome to Banking Accounts Application"
  contact details:
    name: "John Doe"
    email: "johndoe@example.com"
  onCallSupport:
    - 123-456-7890
    - 987-654-3210