build:
  version: "3.0"
cards:
  message: "Welcome to Banking Cards Application"
  contact details:
    name: "John Doe"
    email: "johndoe@example.com"
  onCallSupport:
    - 123-456-7890
    - 987-654-321
