# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Add global configuration
global:
  configMapName: microservices-config

deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

replicaCount: 1

image:
  repository: rudro77/accounts
  tag: 0.0.1-SNAPSHOT

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Enable required features
appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: true

# Add database configuration
database:
  enabled: true
  name: accountsdb
  dbname: accountsdb
  username: root
  password: root
  port: 3306
  storage: 1Gi
  url: jdbc:mysql://accountsdb:3306/accountsdb
  volumeName: mysql-data

# Remove or disable any other mysql configurations
mysql:
  enabled: false

# Ensure we're using the common database
common:
  database:
    enabled: true
