{{- define "common.database" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.database.name }}
spec:
  serviceName: {{ .Values.database.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.database.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.name }}
    spec:
      containers:
      - name: {{ .Values.database.name }}
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.database.password }}
        - name: MYSQL_DATABASE
          value: {{ .Values.database.dbname }}
        ports:
        - containerPort: {{ .Values.database.port }}
          name: mysql
        volumeMounts:
        - name: {{ .Values.database.name }}-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.database.name }}-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.database.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
spec:
  ports:
  - port: {{ .Values.database.port }}
    targetPort: mysql
    name: mysql
  clusterIP: None
  selector:
    app: {{ .Values.database.name }}
{{- end -}} 