# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loans-deployment
serviceName: loans
appLabel: loans
appName: loans

replicaCount: 1

image:
  repository: rudro77/loans
  tag: 0.0.1-SNAPSHOT

containerPort: 8090

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false

# Add database configuration
database:
  enabled: true
  name: loansdb
  dbname: loansdb
  username: root
  password: root
  port: 3306
  storage: 1Gi
  url: jdbc:mysql://loansdb:3306/loansdb
